#import "typst-template-20260409.typ": *

#show: template.with(title:[Class Field Theory])

#title()

= 0908
#eye(supplement:"Goal")[
Describe all abelian extension of number fields.\
i.e. inverse Galois problem for abelian groups.
]

#eye(supplement:"Recall", caption:"Kronecker-Weber Theorem")[
Every abelian extension of the rational numbers is contained in a cyclotomic field.
]

What happens if we replace $QQ$ by a number field $K$?

Denote $op("Cl")(K)$ as the ideal class group of $K$. (Fractional ideals modulo principal ideals.)

#theorem[
  Let $L$ be the maximal unramified abelian extension of a number field $K$. Then $L slash K$ is finite and $op("Gal")(L  slash K) tilde.equiv op("Cl")(K)$.\
  $L$ is called the Hilbert class field of $K$.
]

#eye(supplement:"Recall")[
Let $N>1$ be an integer. $zeta_N$ denotes a primitive $N$-th root of unity. Then\
+ $op("Gal")(QQ(zeta_N) slash QQ) tilde.equiv (ZZ slash N ZZ)^times$.\
+ Suppose $N equiv.not 2 (mod 4)$. Then $p$ is ramified in $QQ(zeta_N)$ if and only if $p | N$.\
+ If $p$ splits completely in $QQ(zeta_N)$, then $p$ is unramified, so the decomposition group is isomorphic to $op("Gal")(kappa(P) slash kappa(p))$.\
  The Frobenius element $op("Frob")(P slash p)$ is the unique element in the decomposition group that acts as $x mapsto x^p$ on the residue field.\
]

It is too restrictive to ask for unramified extensions.\
So we ask for abelian extensions.

== Review $AA_K, II_K = AA_K^times, op("Cl")(K)$
Let $I$ be a fractional ideal in $K$. Then $I$ can be written as $I = P_1^(a_1) ... P_r^(a_r)$, where $P_i$ are prime ideals and $a_i in ZZ$.\
So the group of fractional ideals is a free abelian group generated by the prime ideals.
$
  plus.o.big_P ZZ
$
and $op("Cl")$ is the quotient of $plus.o.big_P ZZ$ by the image of the map $K^times -> plus.o.big_P ZZ$ given by $x |-> (v_P (x))_P$, where $v_P$ is the valuation at $P$.\

Let $U = product_(v:"inf") K_v^times times product_(v:"fin") cal(O)_v^times$. It is an open subgroup of $AA_K^times$.\
Then $AA_K^times slash U$ is exactly $plus.o.big_(v:"fin") ZZ$.
So we have a surjective map $AA_K^times -> op("Cl")(K)$, and the kernel is $U K^times$.\
As the class group corresponds to the maximal unramified abelian extension, we want to shrink $U$ to a smaller open subgroup to detect more abelian extensions.\

[Ray class group]\@Obsidian

#remark[
  This isomorphism shows that $op("Cl")(K, frak(a))$ is finite:\
  By the isomorphism, it is discrete.\
  Also, it is a quotient of $AA_K^1 slash K^times$, which is compact, so it is finite.\
]


#example[
  $op("Cl")(QQ,N) tilde.equiv (ZZ slash N ZZ)^times$.
]
[計算 Cl(Q,N)]\@Obsidian

By Kronecker-Weber, we know that $op("Gal")(QQ^"ab" slash QQ)$ is the inverse limit of $(ZZ slash N ZZ)^times$ over $N$.\
By above, $(ZZ slash N ZZ)^times$ is a quotient of $C_QQ = AA_QQ^times slash QQ^times$.\
Class field theory is saying that we can construct a map from $C_K = AA_K^times slash K^times$ to $op("Gal")(K^"ab" slash K)$ for any number field $K$, and the image of this map is dense.\

#theorem(caption:"Local class field theory")[
  Let $K$ be a local field.
  There is a unique continuous homomorphism
  $
    rho_K : K^times -> op("Gal")(K^"ab" slash K)
  $
  satisfying the following properties:
  + For any $L slash K$ finite abelian extension, the kernel of $rho_K$ is exactly $N_(L slash K)(L^times)$, the norm of $L^times$ in $K^times$.\
  + 
    $
      #diagram(
        $
          K^times edge(->) edge(->,"d") & op("Gal")(K^"ab" slash K) edge(->>) edge(->,"d") & op("Gal")(K^"un" slash K) edge(->,"ld") \
          ZZ edge(->) & op("Gal")(overline(FF_q) slash FF_q)
        $
      )
    $
  + There is a 1-1 correspondence between $U$: an open subgroup of $op("Gal")(K^"ab" slash K)$ and $V$: open subgroup of finite index of $K^times$ given by $U mapsto rho_K^(-1)(U)$.
]


= 0910

#definition(caption:"CSA")[
A (finite-dimensional) central simple algebra (CSA) over a field $K$ is a finite-dimensional $K$-algebra $R$ such that:
- $R$ is a finite-dimensional $K$-algebra.
- $R$ is central: The center of $R$ is exactly $K$.
- $R$ is simple: $R$ has no nontrivial two-sided ideals.
]

#example[
  The matrix algebra $M_n(K)$ is a CSA over $K$.
]
// check simple

#fact(caption:"Wedderburn")[
  Let $A$ be a CSA over $K$. Then there's a central division algebra $D$ s.t.
  $
    A tilde.equiv M_n (D)
  $
  for some $n in ZZ_(>0)$ and $D$ is unique up to isomorphism.
]

#definition[
  Let $A,B$ be two CSAs over $K$. We say $A$ and $B$ are Brauer equivalent if there exist $m,n in ZZ_(>0)$ s.t.
  $
    A times.o_K M_m (K) tilde.equiv B times.o_K M_n (K)
  $
  i.e. their corresponding division algebras are isomorphic. The Brauer equivalence class of $A$ is denoted by $[A]$.\
  The Brauer group $op("Br")(K)$ is the set of Brauer equivalence classes of CSAs over $K$ with the group operation given by tensor product over $K$.\
  Then $[A]^(-1) = [A^"op"]$.
]

The importance of the Brauer group in CFT:\
If $K_v$ is non-archimedean, then $op("Br")(K_v) tilde.equiv QQ slash ZZ$ and it is canonical.

We can write $op("Br")(K_v)$ explicitly as its element is the form $(chi, a)$ where $chi$ is a character of $op("Gal")(K_v^"ab" slash K_v)$ and $a in K_v^times$.\
It help us define a map
$
  rho: & K_v^times & -> & op("Hom")(op("Hom")(op("Gal")(K_v^"ab" slash K_v), QQ slash ZZ), QQ slash ZZ) \
  & a & |-> & (chi mapsto op("inv")(a, chi))
$
and the right hand side is $op("Gal")(K_v^"ab" slash K_v)$ given by Pontryagin duality.\

= Lecture 1: Group cohomology
Let $G$ be a finite group.\
#definition[
+ $M$ is a $G$-module if $M$ is an abelian group with a $G$-action that is compatible with the group structure.\
  We also consider $M$ as a $ZZ[G]$-module.
+ $f:M->N$ is a $G$-module homomorphism if $f$ is a map preserving the $G$-action.
]

#definition[
$C^n (ZZ[G], A) = op("Hom")(ZZ[G]^(n+1), A)$.\
$partial^n: C^n (ZZ[G], A) -> C^(n+1) (ZZ[G], A)$ is defined by
$
  (partial^n f)(g_0, ..., g_(n+1)) = sum_(i=0)^(n+1) (-1)^i f(g_0, ..., hat(g_i), ..., g_(n+1))
$

It defines a cochain complex $(C^n (ZZ[G], A), partial^n)$, and the cohomology of this complex is denoted by $H^n (G, A)$.\
]

= 0917
#definition[
  A $G$-module $B$ is called relatively injective if $B$ is a direct summand of an induced module $op("Ind")_1^G (A)$ for some abelian group $A$.\
]

#corollary[
  A relatively injective $G$-module is acyclic.
]

= Lecture 2: Change of groups
#underline("General"): $f:G' -> G$: group homomorphism of finite groups.\
Let $A$ be a $G$-module. Through $f$, we can make $A$ a $G'$-module. Denote as $f^* A$. This is a functor $f^*: G op("-Mod") -> G' op("-Mod")$.
We have a natural map $f^*: H^n (G, A) -> H^n (G', f^* A)$ for all $n$.

Now consider the case $H arrow.r.hook G$. The pullback map is called the restriction map.
#theorem(caption:"Shapiro lemma")[
$
  H^n (H, A) tilde.equiv H^n (G, op("Ind")_H^G (A))
$
]
#proof[
  By Frobenius reciprocity, we have
  $
    op("Hom")_G (B, op("Ind")_H^G (A)) tilde.equiv op("Hom")_H (B, A)
  $
  For $n=0$: Take $B = ZZ$ with trivial action.\
  Now for $n>0$, take a injective resolution $A -> I^bullet$. By Frobenius reciprocity and the exactness of induction functor, $op("Ind")_H^G (I^bullet)$ is an injective resolution of $op("Ind")_H^G (A)$.\
  Applying the case $n=0$ to $I^bullet$, we get the desired isomorphism since both sides are universal $delta$-functors.
]

Consider another case $H arrow.r.hook G$ and $A$ is a $G$-module. Consider the following map:\
For $n=0$, we have a map $H^0 (H, A|_H) -> H^0 (G, A)$ given by $a mapsto sum_(g in G slash H) g a$.\
Now, $H^n (H, A|_H)$ is a $delta$-functor. We want to show that it's the derived functor of $A |-> A^H = H^0 (H, A|_H)$.\
By the dual of Frobenius reciprocity,
$
  op("Hom")_H (- times.o_H G, I) tilde.equiv op("Hom")_G (-, I)
$
Since $- times.o_H G$ is exact, $I^bullet|_H$ is an injective resolution of $A|_H$. (Restriction is exact.)\
This proves that $H^n (H, A|_H)$ is the derived functor of $A |-> A^H$ hence a universal $delta$-functor.\
As $A |-> H^n (G,A)$ is also a $delta$-functor, we have a natural transformation $H^n (H, A|_H) -> H^n (G, A)$ for all $n$.\