#import "typst-template-20260409.typ": *

#show: template.with(title:[Class Field Theory])

#title()

= 0908
#eye(supplement:"Goal")[
Describe all abelian extension of number fields.\
i.e. inverse Galois problem for abelian groups.
]

#eye(supplement:"Recall", caption:"Kronecker-Weber Theorem")[
Every abelian extension of the rational numbers is contained in a cyclotomic field.
]

What happens if we replace $QQ$ by a number field $K$?

Denote $op("Cl")(K)$ as the ideal class group of $K$. (Fractional ideals modulo principal ideals.)

#theorem[
  Let $L$ be the maximal unramified abelian extension of a number field $K$. Then $L slash K$ is finite and $op("Gal")(L  slash K) tilde.equiv op("Cl")(K)$.\
  $L$ is called the Hilbert class field of $K$.
]

#eye(supplement:"Recall")[
Let $N>1$ be an integer. $zeta_N$ denotes a primitive $N$-th root of unity. Then\
+ $op("Gal")(QQ(zeta_N) slash QQ) tilde.equiv (ZZ slash N ZZ)^times$.\
+ Suppose $N equiv.not 2 (mod 4)$. Then $p$ is ramified in $QQ(zeta_N)$ if and only if $p | N$.\
+ If $p$ splits completely in $QQ(zeta_N)$, then $p$ is unramified, so the decomposition group is isomorphic to $op("Gal")(kappa(P) slash kappa(p))$.\
  The Frobenius element $op("Frob")(P slash p)$ is the unique element in the decomposition group that acts as $x mapsto x^p$ on the residue field.\
]

It is too restrictive to ask for unramified extensions.\
So we ask for abelian extensions.

== Review $AA_K, II_K = AA_K^times, op("Cl")(K)$
Let $I$ be a fractional ideal in $K$. Then $I$ can be written as $I = P_1^(a_1) ... P_r^(a_r)$, where $P_i$ are prime ideals and $a_i in ZZ$.\
So the group of fractional ideals is a free abelian group generated by the prime ideals.
$
  plus.o.big_P ZZ
$
and $op("Cl")$ is the quotient of $plus.o.big_P ZZ$ by the image of the map $K^times -> plus.o.big_P ZZ$ given by $x |-> (v_P (x))_P$, where $v_P$ is the valuation at $P$.\

Let $U = product_(v:"inf") K_v^times times product_(v:"fin") cal(O)_v^times$. It is an open subgroup of $AA_K^times$.\
Then $AA_K^times slash U$ is exactly $plus.o.big_(v:"fin") ZZ$.
So we have a surjective map $AA_K^times -> op("Cl")(K)$, and the kernel is $U K^times$.\
As the class group corresponds to the maximal unramified abelian extension, we want to shrink $U$ to a smaller open subgroup to detect more abelian extensions.\

[Ray class group]\@Obsidian

#remark[
  This isomorphism shows that $op("Cl")(K, frak(a))$ is finite:\
  By the isomorphism, it is discrete.\
  Also, it is a quotient of $AA_K^1 slash K^times$, which is compact, so it is finite.\
]


#example[
  $op("Cl")(QQ,N) tilde.equiv (ZZ slash N ZZ)^times$.
]
[計算 Cl(Q,N)]\@Obsidian

By Kronecker-Weber, we know that $op("Gal")(QQ^"ab" slash QQ)$ is the inverse limit of $(ZZ slash N ZZ)^times$ over $N$.\
By above, $(ZZ slash N ZZ)^times$ is a quotient of $C_QQ = AA_QQ^times slash QQ^times$.\
Class field theory is saying that we can construct a map from $C_K = AA_K^times slash K^times$ to $op("Gal")(K^"ab" slash K)$ for any number field $K$, and the image of this map is dense.\

#theorem(caption:"Local class field theory")[
  Let $K$ be a local field.
  There is a unique continuous homomorphism
  $
    rho_K : K^times -> op("Gal")(K^"ab" slash K)
  $
  satisfying the following properties:
  + For any $L slash K$ finite abelian extension, the kernel of $rho_K$ is exactly $N_(L slash K)(L^times)$, the norm of $L^times$ in $K^times$.\
  + 
    $
      #diagram(
        $
          K^times edge(->) edge(->,"d") & op("Gal")(K^"ab" slash K) edge(->>) edge(->,"d") & op("Gal")(K^"un" slash K) edge(->,"ld") \
          ZZ edge(->) & op("Gal")(overline(FF_q) slash FF_q)
        $
      )
    $
  + There is a 1-1 correspondence between $U$: an open subgroup of $op("Gal")(K^"ab" slash K)$ and $V$: open subgroup of finite index of $K^times$ given by $U mapsto rho_K^(-1)(U)$.
]


= 0910

#definition(caption:"CSA")[
A (finite-dimensional) central simple algebra (CSA) over a field $K$ is a finite-dimensional $K$-algebra $R$ such that:
- $R$ is a finite-dimensional $K$-algebra.
- $R$ is central: The center of $R$ is exactly $K$.
- $R$ is simple: $R$ has no nontrivial two-sided ideals.
]

#example[
  The matrix algebra $M_n(K)$ is a CSA over $K$.
]
// check simple

#fact(caption:"Wedderburn")[
  Let $A$ be a CSA over $K$. Then there's a central division algebra $D$ s.t.
  $
    A tilde.equiv M_n (D)
  $
  for some $n in ZZ_(>0)$ and $D$ is unique up to isomorphism.
]

#definition[
  Let $A,B$ be two CSAs over $K$. We say $A$ and $B$ are Brauer equivalent if there exist $m,n in ZZ_(>0)$ s.t.
  $
    A times.o_K M_m (K) tilde.equiv B times.o_K M_n (K)
  $
  i.e. their corresponding division algebras are isomorphic. The Brauer equivalence class of $A$ is denoted by $[A]$.\
  The Brauer group $op("Br")(K)$ is the set of Brauer equivalence classes of CSAs over $K$ with the group operation given by tensor product over $K$.\
  Then $[A]^(-1) = [A^"op"]$.
]

The importance of the Brauer group in CFT:\
If $K_v$ is non-archimedean, then $op("Br")(K_v) tilde.equiv QQ slash ZZ$ and it is canonical.

We can write $op("Br")(K_v)$ explicitly as its element is the form $(chi, a)$ where $chi$ is a character of $op("Gal")(K_v^"ab" slash K_v)$ and $a in K_v^times$.\
It help us define a map
$
  rho: & K_v^times & -> & op("Hom")(op("Hom")(op("Gal")(K_v^"ab" slash K_v), QQ slash ZZ), QQ slash ZZ) \
  & a & |-> & (chi mapsto op("inv")(a, chi))
$
and the right hand side is $op("Gal")(K_v^"ab" slash K_v)$ given by Pontryagin duality.\

= Lecture 1: Group cohomology
Let $G$ be a finite group.\
#definition[
+ $M$ is a $G$-module if $M$ is an abelian group with a $G$-action that is compatible with the group structure.\
  We also consider $M$ as a $ZZ[G]$-module.
+ $f:M->N$ is a $G$-module homomorphism if $f$ is a map preserving the $G$-action.
]

#definition[
$C^n (ZZ[G], A) = op("Hom")(ZZ[G]^(n+1), A)$.\
$partial^n: C^n (ZZ[G], A) -> C^(n+1) (ZZ[G], A)$ is defined by
$
  (partial^n f)(g_0, ..., g_(n+1)) = sum_(i=0)^(n+1) (-1)^i f(g_0, ..., hat(g_i), ..., g_(n+1))
$

It defines a cochain complex $(C^n (ZZ[G], A), partial^n)$, and the cohomology of this complex is denoted by $H^n (G, A)$.\
]

= 0917
#definition[
  A $G$-module $B$ is called relatively injective if $B$ is a direct summand of an induced module $op("Ind")_1^G (A)$ for some abelian group $A$.\
]

#corollary[
  A relatively injective $G$-module is acyclic.
]

= Lecture 2: Change of groups
#underline("General"): $f:G' -> G$: group homomorphism of finite groups.\
Let $A$ be a $G$-module. Through $f$, we can make $A$ a $G'$-module. Denote as $f^* A$. This is a functor $f^*: G op("-Mod") -> G' op("-Mod")$.
We have a natural map $f^*: H^n (G, A) -> H^n (G', f^* A)$ for all $n$.

Now consider the case $H arrow.r.hook G$. The pullback map is called the restriction map.
#theorem(caption:"Shapiro lemma")[
$
  H^n (H, A) tilde.equiv H^n (G, op("Ind")_H^G (A))
$
]
#proof[
  By Frobenius reciprocity, we have
  $
    op("Hom")_G (B, op("Ind")_H^G (A)) tilde.equiv op("Hom")_H (B, A)
  $
  For $n=0$: Take $B = ZZ$ with trivial action.\
  Now for $n>0$, take a injective resolution $A -> I^bullet$. By Frobenius reciprocity and the exactness of induction functor, $op("Ind")_H^G (I^bullet)$ is an injective resolution of $op("Ind")_H^G (A)$.\
  Applying the case $n=0$ to $I^bullet$, we get the desired isomorphism since both sides are universal $delta$-functors.
]

Consider another case $H arrow.r.hook G$ and $A$ is a $G$-module. Consider the following map:\
For $n=0$, we have a map $H^0 (H, A|_H) -> H^0 (G, A)$ given by $a mapsto sum_(g in G slash H) g a$.\
Now, $H^n (H, A|_H)$ is a $delta$-functor. We want to show that it's the derived functor of $A |-> A^H = H^0 (H, A|_H)$.\
By the dual of Frobenius reciprocity,
$
  op("Hom")_H (- times.o_H G, I) tilde.equiv op("Hom")_G (-, I)
$
Since $- times.o_H G$ is exact, $I^bullet|_H$ is an injective resolution of $A|_H$. (Restriction is exact.)\
This proves that $H^n (H, A|_H)$ is the derived functor of $A |-> A^H$ hence a universal $delta$-functor.\
As $A |-> H^n (G,A)$ is also a $delta$-functor, we have a natural transformation $H^n (H, A|_H) -> H^n (G, A)$ for all $n$.\

= 0922
== Inflation
Let $H lt.closed G$ be a normal subgroup.\
Given a $G$-module $A$, we can make $A^H$ a $G slash H$-module.\
Then we have a natural map
$
  op("inf")_(G slash H): H^n (G slash H, A^H) -> H^n (G, A^H) -> H^n (G, A)
$
#theorem[
  We have an exact sequence
  $
    #diagram(
      $
        0 edge(->) & H^1 (G slash H, A^H) edge(->,op("inf")_(G slash H)) & H^1 (G, A) edge(->,op("res")) & H^1 (H, A)
      $
    ) 
  $
]

= Intermezzo: Spectral sequences (arising from a double complex)
*Set-up*: $M^(bullet, bullet)$: bounded below double complex of abelian groups.\
$
  #diagram(
    $
      & 0 edge(->, "d") & 0 edge(->, "d") & 0 edge(->, "d") \
      0 edge(->) & M^(0,0) edge(->) edge(->, "d") & M^(0,1) edge(->) edge(->, "d") & M^(0,2) edge(->) edge(->, "d") \
      0 edge(->) & M^(1,0) edge(->) edge(->, "d") & M^(1,1) edge(->) edge(->, "d") & M^(1,2) edge(->) edge(->, "d")
    $
  )
$
with 
- $d_(arrow.r) compose d_(arrow.r) = 0$
- $d_(arrow.b) compose d_(arrow.b) = 0$
- $d_(arrow.r) compose d_(arrow.b) + d_(arrow.b) compose d_(arrow.r) = 0$

Define the total complex $M^bullet$ by $M^n = sum_(p+q=n) M^(p,q)$ and $d = d_(arrow.r) + d_(arrow.b)$.\
We want to compute the cohomology of $M^bullet$.\
The strategy is to filter $M^bullet$ by $p$ and $q$ and get two spectral sequences.\
Define $F^i M^n = sum_(p >= i) M^(p,n-p)$.\
Then
$
  F^i H^n = (Z^n + F^i M^n) + B^n slash B^n subset H^n
$
It gives a filtration of $H^n$:
$
  0 subset F^n H^n subset F^(n-1) H^n subset ... subset F^0 H^n = H^n
$


- Page 0: $E_0^(p,q) = M^(p,q)$\
- Page 1: $E_1^(p,q) = H^q (M^(p, bullet))$ with the differential $d_1^(p,q): E_1^(p,q) -> E_1^(p+1,q)$ induced by $d_(arrow.r)$.\
- Page 2: $E_2^(p,q) = H^p (E_1^(bullet, q))$ with the differential $d_2^(p,q): E_2^(p,q) -> E_2^(p+2,q-1)$ induced by $d_(arrow.b)$.\
#eye[
  The map is given by:\
  For $[x] in E_2^(p,q)$, we have $x in M^(p,q)$ s.t. $d_(arrow.r) x = 0$ and $d_(arrow.b) x = d_(arrow.r) (-y)$, for some $y in M^(p+1,q-1)$. Then $d_2^(p,q)([x]) = d_1^(p+1,q-1)([y])$.
]
Inductively, we can define
$
  E_r^(p,q) = op("ker")(d_r^(p,q)) slash op("im")(d_r^(p-r,q+r-1))
$
and
$
  d_r^(p,q): E_r^(p,q) -> E_r^(p+r,q-r+1)
$
For a fixed $(p,q)$, the sequence $E_r^(p,q)$ stabilizes for $r$ large enough. Denote the stable value by $E_oo^(p,q)$.\
If for some $x in M^(p,q)$, we have $d_arrow.r x = 0$ and $d_arrow.b x = 0$, i.e. $d x = 0$. Then $d_n (x) = 0$ for all $n$, so $[x] in E_oo^(p,q)$.\
Similarly, if $x in M^(p,q), y in M^(p+1,q-1)$ and $d(x+y) = 0$, then $[x+y] in E_oo^(p,q)$.\
In fact,
$
  E_oo^(p,q) = (Z^n inter F^p M^(p+q)) / (Z^n inter F^(p+1) M^(p+q) + B^n inter F^p M^(p+q))
$
which is exactly the $p$-th graded piece of the filtration of $H^n$ i.e. $(F^p H^n) / (F^(p+1) H^n)$.

Now, for lower degree terms, we have
- $F^1 H^1 = E_oo^(1,0)$
- $H^1 slash F^1 H^1 = E_oo^(0,1)$
- $F^2 H^2 = E_oo^(2,0)$
i.e.
$
  #diagram(
    $
      0 edge(->) & E_oo^(1,0) edge(->) & H^1 edge(->) & E_oo^(0,1) edge(->) & 0
    $
  )
$
We have $E_oo^(1,0) = E_2^(1,0)$ and $E_oo^(0,1) = ker (d_2^(0,1))$.\
Also, $E_oo^(2,0) = op("coker")(d_2^(0,1))$.\
So we have an exact sequence
$
  #diagram(
    $
      0 edge(->) & E_2^(1,0) edge(->) & H^1 edge(->) & E_2^(0,1) edge(->, op(d_2)) & E_2^(2,0) edge(->) & H^2
    $
  )
$
#theorem(caption:"Grothendieck spectral sequence")[
  Let $cal(A), cal(B), cal(C)$ be three abelian categories.\
  $F: cal(A) -> cal(B)$ and $G: cal(B) -> cal(C)$ be two additive left-exact functors.\
  Assume that
  - $cal(A), cal(B)$ have enough injectives.
  - $F$ sends injective objects of $cal(A)$ to $G$-acyclic objects of $cal(B)$.
Then
$
  E_2^(p,q) = (R^p G)(R^q F)(A) ==> R^(p+q) (G compose F)(A)
$
]
For $A in cal(A)$, take an injective resolution $A -> I^bullet$.\
Then $F(I^bullet)$ is a acyclic complex in $cal(B)$.\
#fact[
  There is a double complex $J^(p,q)$ s.t. $J^(p,bullet)$ is an injective resolution of $F(I^p)$ for all $p$.
]

#example[
  - $cal(A) = "Mod"_G, cal(B) = "Mod"_(G slash H), cal(C) = "Ab"$.\
  - $F(A) = A^H, G(B) = B^(G slash H)$.\
  Then $R^p G = H^p (G slash H, -)$, $R^q F = H^q (H, -)$, and $R^(p+q) (G compose F) = H^(p+q) (G, -)$.\
  So we have a spectral sequence
  $
    #diagram(
      $
        0 edge(->) & E_2^(1,0) edge(->) & H^1 edge(->) & E_2^(0,1) edge(->, op(d_2)) & E_2^(2,0) edge(->) & H^2
      $
    )
  $
  which can be rewritten as
  $
    #diagram(
      spacing: 0.7cm, 
      $
        0 edge(->) & H^1 (G slash H, A^H) edge(->, op("inf")_(G slash H)) & H^1 (G, A) edge(->, op("res")) & H^1 (H, A)^(G slash H) edge(->, op(d_2)) & H^2 (G slash H, A^H) edge(->) & H^2 (G, A)
      $
    )
  $
]